import type { ProductSource } from "@/lib/products";
import type { Producer } from "@/lib/producers";
/** Editorial text/images: read-only kabia-2.0/content/producers.ts. Preserve PLACEHOLDER markers. */
export type SourceProducer = Omit<Producer, "createdAt"> & { source: ProductSource; desc: string };
export const producerCollections: Record<ProductSource, SourceProducer[]> = {
"ciftlik": [
  {
    "id": "editorial:kabia-ciftligi",
    "slug": "kabia-ciftligi",
    "name": "Kabia Çiftliği",
    "source": "ciftlik",
    "productType": "Badem",
    "region": "Sabırlar · Geyve / Sakarya",
    "photoUrl": "/images/kabia-badem.jpeg",
    "desc": "Organik sertifikalı, ekolojik hasadımız.",
    "story": "Kabia Çiftliği'nde her şeyden önce toprağı düşündük. Bizim için tarımın başlangıcı ağaç değil, toprak. Toprağın içindeki milyonlarca canlıyı — bakterileri, mantarları, yararlı fungusları — çoğaltmak; toprağı yeniden yaşayan bir ekosistem haline getirmek asıl işimiz. Önce toprağı iyileştirmeye çalışıyoruz. Canlanan, gelişen toprak ağaçları zaten kendisi besleyip büyütüyor.\n\nDışarıdan hiçbir girdi yok. Organik üretimde kullanımı sertifikalı olsa bile, gübre anlamında bahçeye hiçbir şey almıyoruz. Otları biçmiyoruz, toprağı sürmüyoruz. Doğayı kontrol etmeye değil, taklit etmeye çalışıyoruz; üretimimizi doğanın kendi döngüsüne emanet ediyoruz. Tüm girdilerimiz doğadan ve kendi bahçemizden: kompost, kompost gübresi ve kompost çayı.\n\n946 Marinada ağacı. Her hasat, toprağa verdiğimiz emeğin karşılığı — bir yılın değil, yılların hikâyesi.",
    "productionPlace": null,
    "method": null,
    "inputs": null,
    "certificates": null,
    "whySelected": null
  }
],
"secki": [
  {
    "id": "editorial:geyce-setce-findik",
    "slug": "geyce-setce-findik",
    "name": "Geyve — Setçe Köyü Aile Bahçesi",
    "source": "secki",
    "productType": "Fındık",
    "region": "Setçe Köyü — Aile Bahçesi",
    "photoUrl": "/images/acik-findik1.jpg",
    "desc": "Sade, doğal ve olduğu gibi.",
    "story": "Göktepe’nin Eteğinde Üç Nesillik Bir Miras — Kabia ekosisteminde her üreticinin bir hikayesi, her toprağın bir hafızası vardır. Setçe Köyü’nün Sisli Göktepe dağ yamaçlarına vardığınızda, yeşilin en derin tonuyla karşılar sizi Engin Abi’nin bahçesi. Burası sadece fındık ağaçlarının dizildiği bir arazi değil; üç nesildir kimyasal tek bir damla zehir girmemiş, mantar ağının ve toprak altı canlılığının özgürce nefes aldığı canlı bir orman ekosistemidir.\n\nBiz Kabia olarak toprağı sürmeden, onu sentetik gübrelerle zorlamadan, doğanın kendi dengesini koruyarak üretim yapmanın peşindeyiz. Engin Abi de bu felsefeyi Göktepe’nin sert ama cömert coğrafyasında yıllardır bizzat yaşayan, toprağın kadim bilgesidir.\n\nEngin Abi’nin Ağzından: “Biz Toprağa Efendi Olmaya Değil, Çırak Olmaya Geldik”\n\n“Bu dağın yamacında dedem fındık toplarken de sis aynı böyle çökerdi. Ben bu bahçede büyüdüm, çocukluğum ocak diplerindeki yaprak kompostlarının içinde geçti.\n\n‘Millet ilacı basıyor, sen neden kullanmıyorsun?’ diye soruyorlar. Dedem zehirsiz teslim etti, babam tek gram suni gübre atmadan büyüttü. İki çuval fazla için Göktepe’nin canlısını nasıl zehirleyeyim?\n\nBiz zehir atmayız. Dökülen yaprak, çürüyen dal gübremizdir. Ağacın suyunu, rüzgarını doğru okursan hakkını verir. Bizim fındığın tadı bundandır; kimyasal değil, Göktepe’nin rüzgarı kalır.”\n\nNot: Engin Abi’nin bahçesi organik sertifikalı değil, doğal üretimdir — yerinde gördüğümüz, tanıdığımız üretim.",
    "productionPlace": null,
    "method": null,
    "inputs": null,
    "certificates": null,
    "whySelected": null
  },
  {
    "id": "editorial:ege-ceviz",
    "slug": "ege-ceviz",
    "name": "Kayadibi Köyü Aile Bahçesi",
    "source": "secki",
    "productType": "Ceviz",
    "region": "Kayadibi Köyü Aile Bahçesi",
    "photoUrl": "/images/acik-ceviz1.jpg",
    "desc": "Doğal üretim.",
    "story": "Kayadibi Köyü'nde Ertuğrul'un bahçesinde 210 ceviz ağacı var. Budama elle, hasat elle, kurutma gölgede tel ızgaralarda. Kabuk çatlamadan, içi tam kurumadan çuvala girmez.\n\n\"Ceviz sabır ister,\" diyor Ertuğrul. \"Dalından düşeni değil, dalında olanı beklersin. Erken toplarsan içi buruşur, geç kalırsan küflenir. Penceresi dardır, o pencereyi kaçırmayacaksın.\"\n\nBiz Kabia'da Ertuğrul'un cevizini bu yüzden seçtik: kabuklu, el ayıklaması, katkısız. Hızlı değil, doğru hasat.",
    "productionPlace": null,
    "method": null,
    "inputs": null,
    "certificates": null,
    "whySelected": null
  },
  {
    "id": "editorial:anadolu-bal",
    "slug": "anadolu-bal",
    "name": "Kılıçkaya Vadisi Balı",
    "source": "secki",
    "productType": "Bal",
    "region": "Kılıçkaya Vadisi — Sabit kovan",
    "photoUrl": "/images/acik-bal1.jpg",
    "desc": "Gezgin değil, sabit kovan. Aynı flora, aynı rakım.",
    "story": "Kılıçkaya Vadisi'nde, Sabırlar Kayadibi'nde Yasin'in 78 kovanı var. Arıcı gezgin değil; kovanlar aynı rakımda, aynı florada, aynı yerde duruyor. Yasin, \"Arı ne topladıysa o,\" diyor — şeker yok, erken hasat yok, bal olgunlaşıp sırlanmadan alınmaz.\n\n78 kovan az değil, ama Yasin hepsini tek tek tanır. Hangi kovanın o yıl nasıl çalıştığını, hangi çiçeğe gittiğini bilir. Bal, kovanın takvimiyle alınır; bizim takvimimizle değil.\n\nBiz Kabia'da bu balı bu yüzden seçtik: gezgin değil sabit kovan, aynı flora aynı rakım. Olgun hasat, katkısız.",
    "productionPlace": null,
    "method": null,
    "inputs": null,
    "certificates": null,
    "whySelected": null
  },
  {
    "id": "editorial:akinci-ihlamur",
    "slug": "akinci-ihlamur",
    "name": "Geyve — Akıncı Köyü",
    "source": "secki",
    "productType": "Ihlamur",
    "region": "Geyve / Akıncı Köyü — Orman",
    "photoUrl": "/images/acik-ihlamur1.jpg",
    "desc": "Doğal ürün.",
    "story": "Geyve Akıncı Köyü'nde Salih, Haziran sabahları erkenden bahçeye çıkar. Ihlamur ağaçları yüksektir — çiçekler yukarıda, ulaşmak zordur. Merdiven, uzun sırık, sabır. Kolay toplanan çiçek değil; o yüzden kıymetlidir.\n\nSalih'in ıhlamuru doğaldır: ilaç yok, gübre yok — ağaç kendi halinde, çiçek kendi zamanında. Çiçekler sabah serinliğinde, henüz tam kurumamışken tek tek elle toplanır; dal kırılmaz, ağaç yorulmaz. Aynı gün gölgede, temiz bezler üzerinde ağır ağır kurutulur — güneşte değil, gölgede, çünkü ıhlamurun rengi ve kokusu gölgede saklanır.\n\nBiz Kabia'da Salih'in ıhlamurunu bu yüzden seçtik: sadece çiçek ve yaprak, ne aroma verici ne koruyucu. Her paket, hangi gün hangi yamaçtan toplandığı yazılarak kapanır.",
    "productionPlace": null,
    "method": null,
    "inputs": null,
    "certificates": null,
    "whySelected": null
  }
],
"mutfak": [
  {
    "id": "editorial:domates-salcasi",
    "slug": "domates-salcasi",
    "name": "Domates Salçası",
    "source": "mutfak",
    "productType": "Salça",
    "region": "Geyve — Mevsiminde",
    "photoUrl": "/images/acik-domates1.jpg",
    "desc": "Mevsiminde olgunlaşan domatesler, kazanda ağır ağır koyulaşır.",
    "story": "Geyve'de Ağustos ortasında domatesler dalında kızarınca toplanır. Sabah serinliğinde elde doğranır, büyük kazanlara konur ve saatlerce ağır ağır kaynatılarak koyulaşır. Geyve'de salça güneşte kurutulmaz; güneşte kalanı daha kıvamlı kaçar, bizimki kazan salçasıdır. İçinde sadece domates ve kaya tuzu var; kıvamına gelince cam kavanozlara konur. Koruyucu yok, hızlandırıcı yok. Her kavanozun üzerine hasat haftası yazılır — aynı mutfakta, yıllardır aynı eller yapar.",
    "productionPlace": null,
    "method": null,
    "inputs": null,
    "certificates": null,
    "whySelected": null
  },
  {
    "id": "editorial:elma-sirkesi",
    "slug": "elma-sirkesi",
    "name": "Elma Sirkesi",
    "source": "mutfak",
    "productType": "Sirke",
    "region": "Geyve — Doğal Fermentasyon",
    "photoUrl": "/images/acik-elmasirkesi1.jpg",
    "desc": "Geyve'nin elmalarından, annelerimizin yaptığı gibi.",
    "story": "Geyve elmalarından, anne usulü. Elmalar sonbaharda tam olgunlaşınca toplanır, yıkanır, doğranır ve doğal fermentasyona bırakılır. Filtre edilmez, tortulu kalır. Sirke anası ile birlikte cam kavanozlarda 6 ay dinlenir, sonra süzülmeden şişelenir. Keskin değil, yumuşak; hızlı sirke değil, sabır sirkesi.",
    "productionPlace": null,
    "method": null,
    "inputs": null,
    "certificates": null,
    "whySelected": null
  },
  {
    "id": "editorial:alic-sirkesi",
    "slug": "alic-sirkesi",
    "name": "Alıç Sirkesi",
    "source": "mutfak",
    "productType": "Sirke",
    "region": "Geyve — Doğal Fermentasyon",
    "photoUrl": "/images/acik-alic1.jpg",
    "desc": "Geyve alıçlarından, doğal fermentasyonla.",
    "story": "Geyve alıçlarından, elma sirkesi gibi ama daha buruk, daha derin. Alıçlar sonbaharda tam olgunlaşınca tek tek toplanır, ezilir ve doğal fermentasyona bırakılır. Filtre edilmez, tortulu kalır. Sirke anası ile 6 ay dinlenir, sonra süzülmeden şişelenir. Katkı yok, hızlandırma yok. Her şişe hangi alıç bahçesinden geldiği yazılarak kapanır.",
    "productionPlace": null,
    "method": null,
    "inputs": null,
    "certificates": null,
    "whySelected": null
  },
  {
    "id": "editorial:eriste",
    "slug": "eriste",
    "name": "Erişte",
    "source": "mutfak",
    "productType": "Erişte",
    "region": "Geyve — Elde Kesme",
    "photoUrl": "/images/acik-eriste1.jpg",
    "desc": "Un, yumurta ve tuz. Ovalarda kurutulan yufka, elle kesilir.",
    "story": "Un, yumurta ve tuz — başka bir şey yok. Hamur sabah yoğrulur, oklavayla açılır, yufka olur, Geyve ovalarında güneşte kurur. Kuruyan yufka elde kesilir, ince şeritler halinde doğranır. Makine yok, paketleme telaşı yok. Aynı mutfakta, aynı tezgahta yıllardır aynı eller keser; her erişte aynı sabrı taşır.",
    "productionPlace": null,
    "method": null,
    "inputs": null,
    "certificates": null,
    "whySelected": null
  },
  {
    "id": "editorial:tarhana",
    "slug": "tarhana",
    "name": "Tarhana",
    "source": "mutfak",
    "productType": "Tarhana",
    "region": "Geyve — Geleneksel",
    "photoUrl": "/images/acik-tarhana1.jpg",
    "desc": "Domates, biber, yoğurt ve un. Geleneksel tarhana fermantasyonu.",
    "story": "Domates, kırmızı biber, yoğurt ve un bir araya gelir. Taraklı usulü tarhana 3-4 gün fermente olur — her gün yoğrulur, havalandırılır, ekşitilir. Sonra ince serilir, güneşte kurutulur, elle kırılır, toz olur. Kışın çorbası, yazın emeği. Her tarhana aynı tarife değil, aynı mutfağın eline ve sabrına aittir.",
    "productionPlace": null,
    "method": null,
    "inputs": null,
    "certificates": null,
    "whySelected": null
  }
],
};
export const sourceProducers = Object.values(producerCollections).flat();
