import type { Metadata, Viewport } from "next";
import { headers } from "next/headers";
import { site } from "@/lib/site";
import { getPublicSettings } from "@/lib/settings";
import { getPublishedTheme } from "@/lib/theme-settings";
import { ALL_FONT_VARIABLES } from "@/lib/fonts";
import { ThemeVars } from "@/components/theme/theme-vars";
import { Providers } from "@/components/providers";
import { WhatsAppFloat } from "@/components/layout/whatsapp-float";
import { themeInitScript } from "@/lib/theme";
import "./globals.css";

/**
 * Site metadata, with the default title, description and social image read from
 * the admin SEO settings. `getPublicSettings` is tag-cached and falls back to
 * the previously hard-coded copy, so this stays a static read — it introduces no
 * per-request work and no dynamic rendering.
 */
export async function generateMetadata(): Promise<Metadata> {
  const settings = await getPublicSettings();

  return {
    metadataBase: new URL(site.url),
    title: {
      default: settings.seoDefaultTitle,
      template: `%s | ${settings.storeName}`,
    },
    description: settings.seoDefaultDescription,
    keywords: [
      "Kabia Ekolojik",
      "organik badem",
      "kabuklu badem",
      "Marinada badem",
      "doğal fındık",
      "kabuklu fındık",
      "kabuklu ceviz",
      "ciğ badem",
      "doğal bal",
      "Kılıçkaya balı",
      "ıhlamur",
      "alıç sirkesi",
      "elma sirkesi",
      "domates salçası",
      "erişte",
      "tarhana",
      "ekolojik tarım",
      "organik tarım",
      "Geyve",
      "Sakarya",
      "Kılıçkaya",
    ],
    authors: [{ name: "Kabia Ekolojik", url: site.url }],
    creator: "Kabia Ekolojik",
    publisher: "Epilantis Kozmetik Estetik Medikal Sanayi Dış Tic. Ltd. Şti.",
    formatDetection: { email: false, address: false, telephone: false },
    category: "organik gıda, ekolojik tarım",
    classification: "Ekolojik Tarım, Organik Gıda",
    alternates: {
      canonical: "/",
      languages: { "tr-TR": "/" },
    },
    openGraph: {
      type: "website",
      locale: "tr_TR",
      alternateLocale: ["en_US"],
      url: site.url,
      siteName: settings.storeName,
      title: settings.seoDefaultTitle,
      description: settings.seoDefaultDescription,
      images: [
        {
          url: settings.seoSocialImage,
          width: 1536,
          height: 2040,
          alt: "Kurumaya serilmiş kabuklu Kabia bademleri",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: settings.seoDefaultTitle,
      description: settings.seoDefaultDescription,
      images: [settings.seoSocialImage],
      creator: "@kabiaekolojik",
    },
    robots: {
      index: true,
      follow: true,
      googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1, "max-video-preview": -1 },
    },
    verification: { google: process.env.NEXT_PUBLIC_GOOGLE_VERIFICATION || undefined },
  };
}

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f4f1e8" },
    { media: "(prefers-color-scheme: dark)", color: "#12150f" },
  ],
};

/** Organization data limited to facts from the existing Kabia project. */
const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: site.name,
  url: site.url,
  logo: `${site.url}/images/logo.svg`,
  email: site.email,
  telephone: site.phone,
  address: {
    "@type": "PostalAddress",
    addressLocality: "Geyve",
    addressRegion: "Sakarya",
    postalCode: "54700",
    streetAddress: "Sabırlar",
    addressCountry: "TR",
  },
  sameAs: [site.social.instagram, site.social.facebook, site.social.x].filter(Boolean),
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: site.name,
  url: site.url,
  inLanguage: "tr-TR",
  publisher: { "@type": "Organization", name: site.name, logo: { "@type": "ImageObject", url: `${site.url}/images/logo.svg` } },
  potentialAction: {
    "@type": "SearchAction",
    target: `${site.url}/magaza?q={search_term_string}`,
    "query-input": "required name=search_term_string",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Paralel: theme = cache'li RPC, headers = sync; seri beklemeyi önle
  const [theme, h] = await Promise.all([getPublishedTheme(), headers()]);
  // SEC-09: Read the per-request nonce generated by the proxy for CSP.
  // This is used on inline scripts (theme init + JSON-LD) so they pass
  // the nonce-based CSP without 'unsafe-inline'.
  // Turbopack dev may briefly serve stale HTML where x-nonce is "" – treat
  // empty string as missing to avoid `nonce=""` hydration mismatch.
  const rawNonce = h.get("x-nonce");
  const nonce = rawNonce && rawNonce.length > 0 ? rawNonce : undefined;

  return (
    <html
      lang="tr"
      className={`${ALL_FONT_VARIABLES} h-full`}
      suppressHydrationWarning
    >
      <head>
        {/* Applies the stored light/dark choice before first paint. */}
        <script
          dangerouslySetInnerHTML={{ __html: themeInitScript }}
          nonce={nonce}
          suppressHydrationWarning
        />
        {/* Applies the published theme variables before first paint. */}
        <ThemeVars theme={theme} />
      </head>
      <body className="min-h-full flex flex-col">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
          nonce={nonce}
          suppressHydrationWarning
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
          nonce={nonce}
          suppressHydrationWarning
        />
        <Providers>
          {children}
          <WhatsAppFloat />
        </Providers>
      </body>
    </html>
  );
}
